### ISSUE TITLE
RequestId plugin, custom header name doesn't work

### ISSUE THREAD

**Issue by c0b41** [vicanso/pingap#113]
header key or header_name none of them change the header name

```toml
[plugins.customReqId]
algorithm = "nanoid"
category = "request_id"
size = 8  
header = "X-Foo-Id"  
header_name = "X-Foo-Id"
```

**Comment by vicanso** [comment]
Did you add the plugin to location? 

```yaml
[plugins.customReqId]
algorithm = "nanoid"
category = "request_id"
header_name = "X-Foo-Id"
size = 8



[locations.pingap]
plugins = ["customReqId"]
proxy_set_headers = ["Host:pingap.io"]
upstream = "pingap"
```

My test result: 

```
 headers: {
    "host": "127.0.0.1:6118",
    "connection": "keep-alive",
    "cache-control": "max-age=0",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Safari/537.36",
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
    "sec-fetch-site": "none",
    "sec-fetch-mode": "navigate",
    "sec-fetch-user": "?1",
    "sec-fetch-dest": "document",
    "accept-encoding": "gzip, deflate, br, zstd",
    "accept-language": "en,zh-CN;q=0.9,zh;q=0.8,en-US;q=0.7,zh-TW;q=0.6",
    "x-foo-id": "O6x2Kco-"
}
```

**Comment by c0b41** [comment]
Yes, i'm using windows binary pingap version 0.10.7

```toml
[basic]
log_format_json = false
log_level = "INFO"
name = "foo_web"

[servers.public_http]
addr = "0.0.0.0:80"
locations = ["web"]

[upstreams.bar]
addrs = ["example.com"]

[locations.web]
host = "foo.local"
path = "/"
plugins = ["customReqId", "admin"]
upstream = "bar"

[plugins.customReqId]
algorithm = "nanoid"
category = "request_id"
header_name = "X-Foo-Id"
header = "X-Foo-Id"
size = 8

[plugins.admin]
authorizations = ["YWRtaW46MTIzNDU2"]
category = "admin"
path = "/pingap"
```

Response headers
```
HTTP/1.0 400 Bad Request
Server: AkamaiGHost
Mime-Version: 1.0
Content-Type: text/html
Content-Length: 312
Expires: Thu, 08 May 2025 15:16:27 GMT
Date: Thu, 08 May 2025 15:16:24 GMT
Connection: keep-alive
x-request-id: -Y_jsE0z
```
