### ISSUE TITLE
多端口监听无法访问静态资源

### ISSUE THREAD

**Issue by happytrudy** [vicanso/pingap#126]
[locations.static]
plugins = [
    "pingap:acceptEncodingAdjustment",
    "staticServe",
]

[plugins.staticServe]
category = "directory"
path = "/etc/pingap/web"
index = ["index.php", "index.html", "index.htm", "index.nginx-debian.html"]

 
[servers.main]
addr = "127.0.0.1:60176,[::1]:60176,0.0.0.0:60178,[::]:60178"
locations = ["static"]

当addr监听多个端口地址的时候 http://无法访问 每个端口都无法访问静态资源
查看端口都有监听 但是无法访问
已经确认没开防火墙

**Comment by vicanso** [comment]
index 现在只支持单文件，不支持列表形式。我刚试过监听的多个端口均可以访问：

```toml
[locations.static]
plugins = [
    "pingap:acceptEncodingAdjustment",
    "staticServe",
]

[plugins.staticServe]
category = "directory"
index = "index.html"
path = "~/Downloads"
step = "request"

[servers.test]
addr = "127.0.0.1:60176,[::1]:60176,0.0.0.0:60178,[::]:60178"
locations = ["static"]
```
