### ISSUE TITLE
Io error failed to lookup address information: Temporary failure in name resolution, service-graphql:8081(upstream:graphql)

### ISSUE THREAD

**Issue by Hareramrai** [vicanso/pingap#16]
I'm getting `Io error failed to lookup address information: Temporary failure in name resolution` and my configuration looks like this. 

````toml
[locations.graphql]
client_max_body_size = "50.0 MB"
host = "http://service-graphql:8081"
path = "redmine/dev/graphql"

[servers.redmine]
addr = "127.0.0.1:8089"
threads = 8

[upstreams.graphql]
addrs = ["service-graphql:8081"]

````
`service-graphql` is the name of the docker service in the docker-compose file.

Please let me know if you need any more information.
