### ISSUE TITLE
nginx try_files  如何替代？？？

### ISSUE THREAD

**Issue by bxvs888** [vicanso/pingap#17]
location / {
   try_files $uri /index.html;
   root  /opt/acm/modules/next-ui/;
 }

**Comment by vicanso** [comment]
http://pingap.io/pingap-zh/docs/plugin#directory

可使用静态目录服务的插件来处理：

```toml
[plugins.downloadsServe]
category = "directory"
charset = "utf-8"
chunk_size = 4096
index = "index.html"
max_age = "1h"
path = "~/Downloads"
```
