### ISSUE TITLE
Do you have plan to add websocket proxy support?

### ISSUE THREAD

**Issue by Akagi201** [vicanso/pingap#6]
I am not sure if websocket can be easily supported

**Comment by vicanso** [comment]
`Pingora` supports gRPC and websocket proxying, athough I haven't used websocket proxy, but I think it should be usable.

**Comment by Akagi201** [comment]
In web3 area, the most use cases are http and websocket rpcs. I am not sure whether websocket proxy can reuse the most logic(code) of http.

**Comment by Hareramrai** [comment]
Is there any further update on this?

**Comment by vicanso** [comment]
Is there any problem with the websocket proxy？?

**Comment by Hareramrai** [comment]
> Is there any problem with the WebSocket proxy？?

I wasn't able to find any document regarding the websocket. Does it support out of the box?

**Comment by vicanso** [comment]
Yes, you can configure it through the admin web page or toml file. I will provide document later, may be version 0.6.0

**Comment by Hareramrai** [comment]
It would be great if you could share toml config for the same here for the now. Thank you!

**Comment by vicanso** [comment]
```toml
[servers.ws]
addr = "127.0.0.1:6188"
locations = ["ws"]

[locations.ws]
upstream = "ws"

[upstreams.ws]
addrs = ["124.222.224.186:8800"]
```

I tested it on `http://www.websocket-test.com/`

<img width="1174" alt="image" src="https://github.com/vicanso/pingap/assets/437351/8c2756ac-d857-46fe-a669-3b95b137d14b">
