### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by l-7-l** [vicanso/pingap#92]
Unable to start gateway on port 80， is there something wrong with my configuration?
>upstream.toml
```toml
[upstreams.identity]
addrs = ["0.0.0.0:9000"]
discovery = "docker"
health_check = ""
sni = ""

```
>locations.toml
```toml
[locations.identity]
enable_reverse_proxy_headers = true
host = ""
path = "/identity"
proxy_set_headers = ["Access-Control-Allow-Origin:*"]
rewrite = ""
upstream = "identity"

```
> servers.toml
```toml
[servers.server]
access_log = ""
addr = "127.0.0.1:80"
locations = ["identity"]
```
> docker-compose
```docker-compose
  pingap:
    image: vicanso/pingap
    ports:
      - ${PINGAP_ADMIN_PORT:-3018}:3018
      - ${GATEWAY_PORT:-80}:80
      - ${GATEWAY_SSH_PORT:-443}:443
    environment:
      - PINGAP_ADMIN_ADDR=0.0.0.0:3018
      - ${PINGAP_ADMIN_USER:-pingap}
      - ${PINGAP_ADMIN_PASSWORD:-123123}
      - ${PINGAP_CONF:-/opt/pingap/conf}
      - ${PINGAP_AUTORESTART:-true}
      - ${PINGAP_AUTORELOAD:-true}
    volumes:
      - ./gateways/pingap:/opt/pingap
```

**Comment by adammakowskidev** [comment]
@l-7-l If the site is to be accessible to the public you must use the address 0.0.0.0
```
[servers.server]
access_log = ""
addr = "0.0.0.0:80"
locations = ["identity"]
```

**Comment by l-7-l** [comment]
@adammakowskidev  Thanks, is my location or upstream configuration wrong?
When I visit http://127.0.0.1/identity/health, I get the error:

```HTTPStatus context: No available upstream for identity cause: InternalError```

locations.toml
```toml
[locations.identity]
enable_reverse_proxy_headers = true
host = ""
path = "/identity"
proxy_set_headers = ["Access-Control-Allow-Origin:*"]
rewrite = "^/identity/ /"
upstream = "identity"

```
upstreams.toml
```toml
[upstreams.identity]
addrs        = ["0.0.0.0:9000"]
discovery    = ""
health_check = ""
sni          = ""

```

**Comment by l-7-l** [comment]
When I use the latest docker image, I get an error:
2025-02-12 10:37:58 error: one or more required arguments were not provided

docker-compose:
```yaml

  pingap:
    image: vicanso/pingap
    restart: always
    ports:
      - ${PINGAP_ADMIN_PORT:-3018}:3018
      - ${GATEWAY_PORT:-80}:80
      - ${GATEWAY_SSH_PORT:-443}:443
    environment:
      - PINGAP_ADMIN_ADDR=0.0.0.0:3018
      - ${PINGAP_ADMIN_USER:-pingap}
      - ${PINGAP_ADMIN_PASSWORD:-123123}
      - ${PINGAP_CONF:-/opt/pingap/conf}
      - PINGAP_AUTORESTART:true
      - PINGAP_AUTORELOAD:true
    volumes:
      - ./gateways/pingap:/opt/pingap
    entrypoint: pingap
```
